version: '3'

services:
  chatserviceapp:
    build: .
    container_name: chat-service-app
    ports:
      - "8080:8080"
      - "50052:50051"
    networks:
      - fclx
    volumes:
      - .:/go/src
    depends_on:
      - chatservicedb
      
  chatservicedb:
    image: mysql:8
    container_name: chat-service-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_test
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - fclx
    volumes:
      - .docker/mysql:/var/lib/mysql

networks:
  fclx:
    external: true